# Generated by Django 5.0.2 on 2024-03-16 01:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=200)),
                ('funcion', models.TextField(max_length=200)),
                ('rol', models.TextField(max_length=200)),
                ('fecha_contrato', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombre_emp', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='post.empleado')),
            ],
        ),
    ]
